### ISSUE TITLE
Using log() instead of CUDAnative.log() gives internal StackOverflow error

### ISSUE THREAD

**Issue by maetshju** [JuliaGPU/CUDAnative.jl#205]
I'm still unsure if this is a better fit here or for the Julia language itself since it's an internal error, so if I should move open this issue somewhere else, please let me know.

Using the documentation's [usage example](https://juliagpu.github.io/CUDAnative.jl/v0.8.3/man/usage.html), we can trigger an internal `StackOverflowError` if we use the `log` function in the kernel.

Using CUDAnative version 0.8.3, CUDAdrv 0.8.3, and Julia 0.7.0-alpha.0, this code

```julia
function kernel_vadd(a, b, c)
    i = (blockIdx().x-1) * blockDim().x + threadIdx().x
    c[i] = a[i] + log(b[i])

    return nothing
end
```
produces this error

```
Internal error: encountered unexpected error in runtime:
StackOverflowError()
save_env at /buildworker/worker/package_linux64/build/src/subtype.c:141
forall_exists_subtype at /buildworker/worker/package_linux64/build/src/subtype.c:1062
jl_subtype_env at /buildworker/worker/package_linux64/build/src/subtype.c:1123
intersect at /buildworker/worker/package_linux64/build/src/subtype.c:1986
intersect_union at /buildworker/worker/package_linux64/build/src/subtype.c:1246
intersect at /buildworker/worker/package_linux64/build/src/subtype.c:1999
intersect_ufirst at /buildworker/worker/package_linux64/build/src/subtype.c:1269 [inlined]
intersect_var at /buildworker/worker/package_linux64/build/src/subtype.c:1360
intersect at /buildworker/worker/package_linux64/build/src/subtype.c:1983
intersect_tuple at /buildworker/worker/package_linux64/build/src/subtype.c:1735 [inlined]
intersect at /buildworker/worker/package_linux64/build/src/subtype.c:2049
intersect_unionall at /buildworker/worker/package_linux64/build/src/subtype.c:1588
intersect at /buildworker/worker/package_linux64/build/src/subtype.c:2035
intersect_all at /buildworker/worker/package_linux64/build/src/subtype.c:2125
jl_type_intersection_env_s at /buildworker/worker/package_linux64/build/src/subtype.c:2233
jl_typemap_intersection_node_visitor at /buildworker/worker/package_linux64/build/src/typemap.c:480
jl_typemap_intersection_visitor at /buildworker/worker/package_linux64/build/src/typemap.c:544
jl_typemap_intersection_visitor at /buildworker/worker/package_linux64/build/src/typemap.c:535
ml_matches at /buildworker/worker/package_linux64/build/src/gf.c:2476
jl_matching_methods at /buildworker/worker/package_linux64/build/src/gf.c:1724
abstract_call_gf_by_type at ./reflection.jl:684
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2140
abstract_call at ./compiler/abstractinterpretation.jl:712
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2140
abstract_eval_call at ./compiler/abstractinterpretation.jl:741
abstract_eval at ./compiler/abstractinterpretation.jl:813
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2140
abstract_interpret at ./compiler/abstractinterpretation.jl:931
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2140
typeinf_work at ./compiler/typeinfer.jl:273
typeinf at ./compiler/typeinfer.jl:407
abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:178
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2140
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:87
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2140
abstract_call at ./compiler/abstractinterpretation.jl:712
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2140
abstract_eval_call at ./compiler/abstractinterpretation.jl:741
abstract_eval at ./compiler/abstractinterpretation.jl:813
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2140
abstract_interpret at ./compiler/abstractinterpretation.jl:931
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2140
typeinf_work at ./compiler/typeinfer.jl:273
typeinf at ./compiler/typeinfer.jl:407
typeinf_frame at ./compiler/typeinfer.jl:96 [inlined]
typeinf_code at ./compiler/typeinfer.jl:191
typeinf_ext at ./compiler/typeinfer.jl:233
jfptr_typeinf_ext_12.clone_1 at /home/maetshju/julia0.7alpha/lib/julia/sys.so (unknown line)
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2140
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1540 [inlined]
jl_apply_with_saved_exception_state at /buildworker/worker/package_linux64/build/src/rtutils.c:257
jl_type_infer at /buildworker/worker/package_linux64/build/src/gf.c:274
jl_compile_linfo at /buildworker/worker/package_linux64/build/src/codegen.cpp:1141
emit_invoke at /buildworker/worker/package_linux64/build/src/codegen.cpp:3106
emit_expr at /buildworker/worker/package_linux64/build/src/codegen.cpp:3956
emit_ssaval_assign at /buildworker/worker/package_linux64/build/src/codegen.cpp:3622
emit_stmtpos at /buildworker/worker/package_linux64/build/src/codegen.cpp:3870 [inlined]
emit_function at /buildworker/worker/package_linux64/build/src/codegen.cpp:6483
jl_compile_linfo at /buildworker/worker/package_linux64/build/src/codegen.cpp:1181
emit_invoke at /buildworker/worker/package_linux64/build/src/codegen.cpp:3106
emit_expr at /buildworker/worker/package_linux64/build/src/codegen.cpp:3956
emit_ssaval_assign at /buildworker/worker/package_linux64/build/src/codegen.cpp:3622
emit_stmtpos at /buildworker/worker/package_linux64/build/src/codegen.cpp:3870 [inlined
]
```

The last few lines seem to print out forever until the program is interrupted:

```
emit_function at /buildworker/worker/package_linux64/build/src/codegen.cpp:6483
jl_compile_linfo at /buildworker/worker/package_linux64/build/src/codegen.cpp:1181
emit_invoke at /buildworker/worker/package_linux64/build/src/codegen.cpp:3106
emit_expr at /buildworker/worker/package_linux64/build/src/codegen.cpp:3956
emit_ssaval_assign at /buildworker/worker/package_linux64/build/src/codegen.cpp:3622
emit_stmtpos at /buildworker/worker/package_linux64/build/src/codegen.cpp:3870 [inlined
]
```

However, using `CUDAnative.log` in the function works as expected:

```julia
function kernel_vadd(a, b, c)
    i = (blockIdx().x-1) * blockDim().x + threadIdx().x
    c[i] = a[i] + CUDAnative.log(b[i])

    return nothing
end
```

Giving the output

```
Test Failed at /home/maetshju/gsoc2018/speech-cnn/testgpu.jl:49
  Expression: a + b ≈ c
   Evaluated: Float32[106.0 28.0 129.0 113.0; 23.0 92.0 51.0 111.0; 76.0 113.0 86.0 110.0] ≈ Float32[21.4886 6.21888 56.3438 91.2189; 5.99573 49.8286 13.7136 68.8286; 28.9318 96.9444 12.3567 21.5326]
ERROR: LoadError: There was an error during testing
in expression starting at /home/maetshju/gsoc2018/speech-cnn/testgpu.jl:49
```

With CUDAnative 0.6.3, CUDAdrv 0.7.8, and Julia 0.6.2, there is a more sensible error when using base `log` in the kernel:

```
ERROR: LoadError: CUDA error: invalid program counter (code #718, ERROR_INVALID_PC)
Stacktrace:
 [1] macro expansion at /home/maetshju/.julia/v0.6/CUDAdrv/src/base.jl:148 [inlined]
 [2] #download!#5(::Bool, ::Function, ::Ptr{Float32}, ::CUDAdrv.Mem.Buffer, ::Int64, ::CUDAdrv.CuStream) at /home/maetshju/.julia/v0.6/CUDAdrv/src/memory.jl:224
 [3] copy!(::Array{Float32,2}, ::CUDAdrv.CuArray{Float32,2}) at /home/maetshju/.julia/v0.6/CUDAdrv/src/array.jl:153
 [4] Array(::CUDAdrv.CuArray{Float32,2}) at /home/maetshju/.julia/v0.6/CUDAdrv/src/array.jl:231
 [5] include_from_node1(::String) at ./loading.jl:576
 [6] include(::String) at ./sysimg.jl:14
 [7] process_options(::Base.JLOptions) at ./client.jl:305
 [8] _start() at ./client.jl:371
while loading /home/maetshju/gsoc2018/speech-cnn/testgpu.jl, in expression starting on line 47
```

From [other issues](https://github.com/JuliaGPU/CUDAnative.jl/issues/93), it looks like base functions vs. the CUDAnative equivalents is a pernicious and tricky problem, but is there a way that this could be caught so that the internal error doesn't happen?

**Comment by maleadt** [comment]
There's a loop (ie. recursion) which breaks uncached compilation, see #122:

```
(gdb) p ctx.name
$2 = 0x7fffe3d43320 "#IOBuffer#306"
(gdb) up 6
#45 0x00007ffff75d515c in emit_ssaval_assign (ctx=..., idx=31, r=0x7fffe61a98f0) at /home/tbesard/Julia/julia-dev/src/codegen.cpp:3604
3604    static void emit_ssaval_assign(jl_codectx_t &ctx, ssize_t idx, jl_value_t *r)
(gdb) p ctx.name
$3 = 0x7fffe3d25b00 "#print_to_string#333"
(gdb) up 6
#51 0x00007ffff75d515c in emit_ssaval_assign (ctx=..., idx=2, r=0x7fffe61a7db0) at /home/tbesard/Julia/julia-dev/src/codegen.cpp:3604
3604    static void emit_ssaval_assign(jl_codectx_t &ctx, ssize_t idx, jl_value_t *r)
(gdb) p ctx.name
$4 = 0x7fffe3d40d68 "#IOBuffer#305"
(gdb) up 6
#57 0x00007ffff75d515c in emit_ssaval_assign (ctx=..., idx=106, r=0x7fffe61a75b0) at /home/tbesard/Julia/julia-dev/src/codegen.cpp:3604
3604    static void emit_ssaval_assign(jl_codectx_t &ctx, ssize_t idx, jl_value_t *r)
(gdb) p ctx.name
$5 = 0x7fffe3d43320 "#IOBuffer#306"
(gdb) up 6
#63 0x00007ffff75d515c in emit_ssaval_assign (ctx=..., idx=31, r=0x7fffe619bcf0) at /home/tbesard/Julia/julia-dev/src/codegen.cpp:3604
3604    static void emit_ssaval_assign(jl_codectx_t &ctx, ssize_t idx, jl_value_t *r)
(gdb) p ctx.name
$6 = 0x7fffe3d25b00 "#print_to_string#333"
(gdb) up 6
#69 0x00007ffff75d515c in emit_ssaval_assign (ctx=..., idx=2, r=0x7fffe619b0b0) at /home/tbesard/Julia/julia-dev/src/codegen.cpp:3604
3604    static void emit_ssaval_assign(jl_codectx_t &ctx, ssize_t idx, jl_value_t *r)
(gdb) p ctx.name
$7 = 0x7fffe3d40d68 "#IOBuffer#305"
(gdb) up 6
#75 0x00007ffff75d515c in emit_ssaval_assign (ctx=..., idx=106, r=0x7fffe619aab0) at /home/tbesard/Julia/julia-dev/src/codegen.cpp:3604
3604    static void emit_ssaval_assign(jl_codectx_t &ctx, ssize_t idx, jl_value_t *r)
(gdb) p ctx.name
$8 = 0x7fffe3d43320 "#IOBuffer#306"
```

> is there a way that this could be caught so that the internal error doesn't happen

No, not at this point. A codegen hook to intercept CodeInfo's being emitted in order to detect cycles might work.

**Comment by maleadt** [comment]
I guess too many people have been bitten by this for me to ignore this. What about

```
$ jj vadd.jl                                                                                                                                                                           *[master] 
ERROR: LoadError: could not compile vadd(CuDeviceArray{Float32,2,CUDAnative.AS.Global}, CuDeviceArray{Float32,2,CUDAnative.AS.Global}, CuDeviceArray{Float32,2,CUDAnative.AS.Global}) for GPU; recursion is not supported

Stacktrace:
 [1] KernelWrapper at /home/tbesard/Julia/CUDAnative/src/execution.jl:56
 [2] log at special/log.jl:290
 [3] throw_complex_domainerror at math.jl:31
 [4] #print_to_string#331 at strings/io.jl:110
 [5] #IOBuffer#304 at iobuffer.jl:111
 [6] #IOBuffer#303 at iobuffer.jl:90
 [7] #print_to_string#331 at strings/io.jl:110
```

**Comment by maetshju** [comment]
That looks wonderful to me. If it's not feasible to write the code to catch it though, I think even just mentioning this in the documentation would help.

**Comment by maleadt** [comment]
Yeah, documentation is always lacking. Feel free to help out with that though, as I tend to focus my time on implementing actual features :-)
