### ISSUE TITLE
`fldmod1` results in unsupported array return type

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDAnative.jl#28]
The following snippet results in IR returning a `[i32,i32]`, something NVPTX cannot handle as of LLVM 3.9.1:

```julia
using CUDAdrv, CUDAnative

function kernel(a, x, y)
    x1, y1 = fldmod1(x, y)
    a[0] = x1 + y1

    return nothing
end

CUDAnative.code_ptx(kernel, Tuple{CuDeviceArray{UInt32,1}, UInt32, UInt32})
```

```
Unknown return type
UNREACHABLE executed at julia/deps/srccache/llvm-3.9.1/lib/Target/NVPTX/NVPTXAsmPrinter.cpp:379!


Thread 1 "julia" received signal SIGABRT, Aborted.
0x00007ffff6cbb04f in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff6cbb04f in raise () from /usr/lib/libc.so.6
#1  0x00007ffff6cbc47a in abort () from /usr/lib/libc.so.6
#2  0x00007ffff3aa57f0 in llvm::llvm_unreachable_internal (msg=0x7ffff5d3db60 "Unknown return type", file=0x7ffff5d3da57 "julia/deps/srccache/llvm-3.9.1/lib/Target/NVPTX/NVPTXAsmPrinter.cpp", line=379)
    at julia/deps/srccache/llvm-3.9.1/lib/Support/ErrorHandling.cpp:118
#3  0x00007ffff522d3c3 in llvm::NVPTXAsmPrinter::printReturnValStr (this=0xd747f0, F=0x246cc38, O=...) at julia/deps/srccache/llvm-3.9.1/lib/Target/NVPTX/NVPTXAsmPrinter.cpp:379
#4  0x00007ffff522f5ab in llvm::NVPTXAsmPrinter::emitDeclaration (this=0xd747f0, F=0x246cc38, O=...) at julia/deps/srccache/llvm-3.9.1/lib/Target/NVPTX/NVPTXAsmPrinter.cpp:627
#5  0x00007ffff5230a28 in llvm::NVPTXAsmPrinter::emitDeclarations (this=0xd747f0, M=..., O=...) at julia/deps/srccache/llvm-3.9.1/lib/Target/NVPTX/NVPTXAsmPrinter.cpp:763
#6  0x00007ffff522de4d in llvm::NVPTXAsmPrinter::emitGlobals (this=0xd747f0, M=...) at julia/deps/srccache/llvm-3.9.1/lib/Target/NVPTX/NVPTXAsmPrinter.cpp:883
#7  0x00007ffff522dbba in llvm::NVPTXAsmPrinter::EmitFunctionEntryLabel (this=0xd747f0) at julia/deps/srccache/llvm-3.9.1/lib/Target/NVPTX/NVPTXAsmPrinter.cpp:456
#8  0x00007ffff449e7ff in llvm::AsmPrinter::EmitFunctionHeader (this=0xd747f0) at julia/deps/srccache/llvm-3.9.1/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:576
#9  0x00007ffff449f183 in llvm::AsmPrinter::EmitFunctionBody (this=0xd747f0) at julia/deps/srccache/llvm-3.9.1/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:842
#10 0x00007ffff44acd38 in llvm::AsmPrinter::runOnMachineFunction (this=0xd747f0, MF=...) at julia/deps/srccache/llvm-3.9.1/include/llvm/CodeGen/AsmPrinter.h:209
#11 0x00007ffff523923b in llvm::NVPTXAsmPrinter::runOnMachineFunction (this=0xd747f0, F=...) at julia/deps/srccache/llvm-3.9.1/lib/Target/NVPTX/NVPTXAsmPrinter.h:327
#12 0x00007ffff3fa6f56 in llvm::MachineFunctionPass::runOnFunction (this=0xd747f0, F=...) at julia/deps/srccache/llvm-3.9.1/lib/CodeGen/MachineFunctionPass.cpp:60
#13 0x00007ffff3d1325f in llvm::FPPassManager::runOnFunction (this=0x486dbc0, F=...) at julia/deps/srccache/llvm-3.9.1/lib/IR/LegacyPassManager.cpp:1526
#14 0x00007ffff3d13575 in llvm::FPPassManager::runOnModule (this=0x486dbc0, M=...) at julia/deps/srccache/llvm-3.9.1/lib/IR/LegacyPassManager.cpp:1547
#15 0x00007ffff3d13d0a in (anonymous namespace)::MPPassManager::runOnModule (this=0x2939480, M=...) at julia/deps/srccache/llvm-3.9.1/lib/IR/LegacyPassManager.cpp:1603
#16 0x00007ffff3d13836 in llvm::legacy::PassManagerImpl::run (this=0x367b6e0, M=...) at julia/deps/srccache/llvm-3.9.1/lib/IR/LegacyPassManager.cpp:1706
#17 0x00007ffff3d14221 in llvm::legacy::PassManager::run (this=0x7fffffffabe0, M=...) at julia/deps/srccache/llvm-3.9.1/lib/IR/LegacyPassManager.cpp:1737
#18 0x00007ffff522731b in LLVMTargetMachineEmit (T=0x3aab7d0, M=0x26f6a90, OS=..., codegen=LLVMAssemblyFile, ErrorMessage=0x7ffdee4b04b0)
    at julia/deps/srccache/llvm-3.9.1/lib/Target/TargetMachineC.cpp:205
#19 0x00007ffff52273bb in LLVMTargetMachineEmitToMemoryBuffer (T=0x3aab7d0, M=0x26f6a90, codegen=LLVMAssemblyFile, ErrorMessage=0x7ffdee4b04b0, OutMemBuf=0x7ffdee4b04c0)
    at julia/deps/srccache/llvm-3.9.1/lib/Target/TargetMachineC.cpp:229
#20 0x00007ffdd452fb3a in ?? ()
#21 0x00007ffdee4b04c0 in ?? ()
#22 0x00007ffdee4b04b0 in ?? ()
#23 0xc2f8aaab3a571500 in ?? ()
#24 0x00007ffdee4b04b0 in ?? ()
#25 0x00007fffffffae38 in ?? ()
#26 0x00007ffdee4b04c0 in ?? ()
#27 0x00007ffdedbb7130 in ?? ()
#28 0x00007ffff7fbd1c8 in ?? ()
#29 0x00007fffffffae10 in ?? ()
#30 0x00007ffdd452fddf in ?? ()
#31 0x00007ffdee3f5090 in ?? ()
#32 0x0000000000000000 in ?? ()


(gdb) f 3
#3  0x00007ffff522d3c3 in llvm::NVPTXAsmPrinter::printReturnValStr (this=0xd747f0, F=0x246cc38, O=...) at julia/deps/srccache/llvm-3.9.1/lib/Target/NVPTX/NVPTXAsmPrinter.cpp:379
379           llvm_unreachable("Unknown return type");

(gdb) call Ty->dump()
[2 x i32]

(gdb) call Ty->getTypeID()
$1 = llvm::Type::ArrayTyID


(gdb) f 13
#13 0x00007ffff3d1325f in llvm::FPPassManager::runOnFunction (this=0x486dbc0, F=...) at julia/deps/srccache/llvm-3.9.1/lib/IR/LegacyPassManager.cpp:1526
1526          LocalChanged |= FP->runOnFunction(F);

(gdb) call F.dump()
; Function Attrs: nounwind
define void @julia_kernel_66759(%CuDeviceArray.0* nocapture readonly, i32, i32) local_unnamed_addr #0 !dbg !11 {
top:
  %ptls_i8 = tail call i8* asm "movq %fs:0, $0;\0Aaddq $$-2680, $0", "=r,~{dirflag},~{fpsr},~{flags}"() #3
  tail call void @llvm.dbg.value(metadata %CuDeviceArray.0* %0, i64 0, metadata !24, metadata !29), !dbg !30
  tail call void @llvm.dbg.value(metadata i32 %1, i64 0, metadata !25, metadata !31), !dbg !30
  tail call void @llvm.dbg.value(metadata i32 %2, i64 0, metadata !26, metadata !31), !dbg !30
  %3 = tail call [2 x i32] @julia_fldmod1_66763(i32 %1, i32 %2) #4, !dbg !30
  %.elt = extractvalue [2 x i32] %3, 0, !dbg !30
  tail call void @llvm.dbg.value(metadata i32 %.elt, i64 0, metadata !27, metadata !31), !dbg !30
  %.elt2 = extractvalue [2 x i32] %3, 1, !dbg !30
  tail call void @llvm.dbg.value(metadata i32 %.elt2, i64 0, metadata !28, metadata !31), !dbg !30
  %4 = add i32 %.elt, %.elt2, !dbg !32
  %5 = getelementptr %CuDeviceArray.0, %CuDeviceArray.0* %0, i64 0, i32 1, !dbg !32
  %6 = load i32*, i32** %5, align 8, !dbg !32, !tbaa !33
  %7 = getelementptr i32, i32* %6, i64 -1, !dbg !32
  store i32 %4, i32* %7, align 8, !dbg !32, !tbaa !36
  ret void, !dbg !38
}
```
```

**Comment by maleadt** [comment]
Works now.
